name: Xcode build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version
      
    - name: Xcode build
      run: |
        cd MovieSwift/
        xcodebuild clean build -scheme MovieSwift -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.0'
